project_id = "mmumfgxngzaivvyqfbed"

[functions.request-password-reset]
verify_jwt = false

[functions.verify-reset-code]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.notify-rdo-delay]
verify_jwt = false

[functions.test-rdo-notification]
verify_jwt = false